import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 10.0

[window]
opacity = 0.9
blur = true
startup_mode = "Maximized"
dynamic_title = true
dynamic_padding = true

[shell]
program = "zsh"
args = ["-l", "-c", "tmux"]
